name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ci
    # strategy:
      # fail-fast: false
      # matrix:
        # run copies of the current job in parallel
        # containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run the Hyvä testing suite
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          # record: true
          # parallel: true
        env:
                    # pass GitHub token to allow accurately detecting a build vs a re-run build
          CYPRESS_VIDEO_UPLOAD_ON_PASSES: 'true'
          CYPRESS_MAGENTO2_SKIP_CHECKOUT: 'true'
          CYPRESS_MAGENTO2_SPEC_SUITE: 'hyva'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_MAGENTO2_BASE_URL: 'https://hyva-demo.elgentos.io'
          # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}